# Generated by Django 6.0.4 on 2026-05-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_notification_titre_notification_type_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20),
        ),
    ]
