# Generated by Django 6.0.4 on 2026-06-13 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_paiement_reference_alter_paiement_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='reference',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='manager_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='validation_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vetement',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vetement',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vetement',
            name='matiere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vetement',
            name='type_marocain',
            field=models.CharField(choices=[('caftan', 'Caftan'), ('takchita', 'Takchita'), ('djellaba', 'Djellaba'), ('jabador', 'Jabador'), ('gandoura', 'Gandoura'), ('selham', 'Selham')], default='caftan', max_length=50),
        ),
        migrations.CreateModel(
            name='MessageManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediteur', models.CharField(choices=[('gestionnaire', 'Gestionnaire'), ('client', 'Client')], max_length=20)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app1.reservation')),
            ],
        ),
    ]
