# Generated by Django 6.0.4 on 2026-06-14 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, '⭐ 1 étoile'), (2, '⭐⭐ 2 étoiles'), (3, '⭐⭐⭐ 3 étoiles'), (4, '⭐⭐⭐⭐ 4 étoiles'), (5, '⭐⭐⭐⭐⭐ 5 étoiles')])),
                ('commentaire', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to=settings.AUTH_USER_MODEL)),
                ('vetement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='app1.vetement')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'vetement')},
            },
        ),
    ]
