# Generated by Django 6.0.4 on 2026-06-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_avis'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetement',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vetement',
            name='est_supprime',
            field=models.BooleanField(default=False),
        ),
    ]
